// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHeH8-Kblz5Lfw2hLqmhu5WWGG4l51Xs4',
    appId: '1:987162434941:web:33c4801b86afdf2622c014',
    messagingSenderId: '987162434941',
    projectId: 'bizapp-1b701',
    authDomain: 'bizapp-1b701.firebaseapp.com',
    storageBucket: 'bizapp-1b701.appspot.com',
    measurementId: 'G-PN2183GNPH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrZQ_4oKCO_4uDOvd35ir24fySJ-42KtU',
    appId: '1:987162434941:android:48b0642133924f5122c014',
    messagingSenderId: '987162434941',
    projectId: 'bizapp-1b701',
    storageBucket: 'bizapp-1b701.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOJOfluq-tq0kBmCZbFfNS3WC_T-0XTW0',
    appId: '1:987162434941:ios:a8757706ed00374c22c014',
    messagingSenderId: '987162434941',
    projectId: 'bizapp-1b701',
    storageBucket: 'bizapp-1b701.appspot.com',
    iosBundleId: 'com.example.businessapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOJOfluq-tq0kBmCZbFfNS3WC_T-0XTW0',
    appId: '1:987162434941:ios:a8757706ed00374c22c014',
    messagingSenderId: '987162434941',
    projectId: 'bizapp-1b701',
    storageBucket: 'bizapp-1b701.appspot.com',
    iosBundleId: 'com.example.businessapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBHeH8-Kblz5Lfw2hLqmhu5WWGG4l51Xs4',
    appId: '1:987162434941:web:76f397c8dddca6d622c014',
    messagingSenderId: '987162434941',
    projectId: 'bizapp-1b701',
    authDomain: 'bizapp-1b701.firebaseapp.com',
    storageBucket: 'bizapp-1b701.appspot.com',
    measurementId: 'G-HNN7BNV92H',
  );
}
